### ISSUE TITLE
iOS 10 Permissions

### ISSUE THREAD

**Issue by bflopez** [rehy/cordova-admob-sdk#1]
Is there a timeline on updating this to AdMob SDK 7.11.0 in accordance to the iOS 10 permissions issue?

**Comment by ratson** [comment]
https://github.com/rehy/cordova-admob-sdk/commit/a5897b186be24b0855a22c1b8d0c4c89e5c33164 has updated the SDK.

Is the issue resolved?

**Comment by bflopez** [comment]
@ratson Thank you. I am currently out of town but will check when I get back this week. I am sure it works but I will get you confirmation.

**Comment by bflopez** [comment]
@ratson Thank you it seems to be working! I really appreciate it.
